### ISSUE TITLE
Add bottom navigations on mobile screen

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#1]
On mobile screen add bottom menu navigation
Add menu icons and link to their respective pages
- Home
- Login
- Explore
- Bookmark
- Profile
- Create post

Pick menu icons and links from sidebar component.

**Comment by MokshagnaV** [comment]
I can work on it. Please assign it to me

**Comment by harshmangalam** [comment]
Awesome. Please raise PR on 1 oct then your pr will be considered by Hacktoberfest.

**Comment by MokshagnaV** [comment]
Thank you.
Till then can i work on other issue?

### I have a doubt.
If i work on other issues too. How it is possible to merge?
don't we get conflicts?

And 

Is this amount of contribution is enough to a count as one PR in hacktoberfest?
