### ISSUE TITLE
Fix flex alignment issues

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#10]
Fix Create post footer alignment issues of icons and button

**Comment by Baburao-sanivada** [comment]
Hello I want to work on the Issue Can you assign the issue to me and can you provide more Description about the issue

**Comment by IrfanshaikH-7** [comment]
Hello!! - if It's okay, I'd like to start working on it. as I already have a command over tailwind CSS, I believe I'll be able to do a great job.

Thank you😊.

**Comment by MyselfAkashYadav** [comment]
would love to contribute on this project , and have a very fantastic grip over tailwind css , and ui libraries ...
could you please assign me this ...will deliver my best work
waiting for a good response .

**Comment by ruskovin** [comment]
I want to contribute to this project . I've already fixed the create post footer alignment of icons and button

**Comment by IrfanshaikH-7** [comment]
hello can i pull request now?
