### ISSUE TITLE
Create 404 not found page

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#11]
For now 404 error from routeLoader and routeAction render default 404 page but  add custom 404 page and render error message with some important public links i.e Home , Login, Explore etc...

**Comment by MokshagnaV** [comment]
I have knowledge on react and tailwind css. But i am new to qwik.
Can i work on it. Can i catch up easily.

**Comment by harshmangalam** [comment]
You can visit qwikcity docs for added custom 404 error page and you can add . If you know react you already know qwik only some api and  component declatation styles varry.

**Comment by MokshagnaV** [comment]
Hey,
I have designed 404 page like this
![image](https://github.com/harshmangalam/qwik-x/assets/92448513/41a2c114-5b6d-4ef4-b0e2-8cce818582b7)

Is it okay? 
If okay i'll create a PR.

Thank you,
Happy Hacktoberfest

**Comment by MokshagnaV** [comment]
I think the issue has been resolved.
I recommend closing the issue @harshmangalam 
Or else if there any adjustments required.
Please let me know, and I am here to help.
