### ISSUE TITLE
Create empty data component

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#13]
Create generic component that will show in place of empty data.
- Add empty data icon
- Add dynamic text (accept as props)

Can be used in place of 
- when there is no data for suggestions
- when there is no data for posts in feed page
- etc...

**Comment by mohanadft** [comment]
Hi I would like to take this, I am just wondering about empty data icon should it be like [this](https://www.flaticon.com/free-icons/no-data)?
Or if you could give me an icon example

**Comment by harshmangalam** [comment]
Yes you can use any svg icon.
