### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Znoy108x** [harshmangalam/qwik-x#15]
I can create an interaction analysis dashboard using Python, Streamlit & Plotly.
Interaction analysis can be done with the Social Media Dataset (Twitter).

**Comment by harshmangalam** [comment]
Awesome , you can proceed let me know if you need any help.

**Comment by Znoy108x** [comment]
> Awesome , you can proceed let me know if you need any help.

I am having some issue uploading the dataset because it's size is 457MB and github allows 100mb.
Should I upload it on google drive and share the link on readme. ??

**Comment by Znoy108x** [comment]
@harshmangalam when i'm doing git push this issue is coming 
<img width="724" alt="image" src="https://github.com/harshmangalam/qwik-x/assets/75539409/aec23a04-dbab-4829-a031-e26d5f7a50fb">

**Comment by harshmangalam** [comment]
Please fork first then create different branch than main and then raise PR. I have mentioned in CONTRIBUTION.md
