### ISSUE TITLE
Show empty text in `/lists/`page

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#21]
If lists have no any data then show 
- Add Empty text for `pinned lists`
- Add Empty text for  `Discover new lists`
- Add empty text for `Your lists`

**Comment by Shreya-0999** [comment]
@harshmangalam Can you assign it to me? I would like to work on it.

**Comment by Shreya-0999** [comment]
I think of something like this. Is it fine with you?
![image](https://github.com/harshmangalam/qwik-x/assets/68765574/e2858ce8-4b85-40d8-a958-1e33e9a66e97)

**Comment by tmatheas** [comment]
@harshmangalam Sorry I haven't noticed that @Shreya-0999 has started working on it..

I have noticed it once I fixed the issue and raised the PR

**Comment by Shreya-0999** [comment]
No problem : )

**Comment by harshmangalam** [comment]
Okay no problem @tmatheas . @Shreya-0999 i will open some more issues today you can pick from there.
