### ISSUE TITLE
Add tooltip in create post section

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#25]
Add toolip in create post modal icon buttons
- Image icon button
- GIF icon button
- Emoji icon button

**Comment by MokshagnaV** [comment]
I would like to work on this
Assign it to me

**Comment by MokshagnaV** [comment]
Here's the preview that of the feature for this issue

[tooltip preview.webm](https://github.com/harshmangalam/qwik-x/assets/92448513/03021a89-e671-43a9-9db2-8bc7387c543f)

If okay I'll open a PR
