### ISSUE TITLE
Add document title in auth page

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#32]
Add document title in `/login` and `/signup` page

For reference check
https://qwik.builder.io/docs/pages/#head-export

**Comment by mohiwalla** [comment]
Hi @harshmangalam, can you please provide the link of the `/login` and `/signup` page? When I tried to reach these on the site you mentioned, got a 404 error :)

And even couldn't find login OR signup pages in [Home page](https://qwik.builder.io/) as well.

![image](https://github.com/harshmangalam/qwik-x/assets/121000462/a078fb40-a2d8-44c0-982d-a68e1cd1bf6b)

**Comment by harshmangalam** [comment]
That is qwik docs link
Open qwik-x link
