### ISSUE TITLE
Add pagination in users suggestions page

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#4]
For now /suggestions  page load all users at once.
Add pagination in /suggestions page.
At once show 10 users and once user click on load more button then fetch the next 10 and show.

**Comment by coder-pink** [comment]
I would to work on this.

**Comment by harshmangalam** [comment]
Thanks @mahabubx7

**Comment by mahabubx7** [comment]
Were you able to seed data using `neon-http`?

**Comment by harshmangalam** [comment]
Nope for now i am just running seed file that create dummy data in db . But in future will use drizzle kit seed once available.

**Comment by mahabubx7** [comment]
> Nope for now i am just running seed file that create dummy data in db . But in future will use drizzle kit seed once available.

Please give me some samples and the guide to populate the database. So I can test the paginate feature for /suggestions route/page

> Waiting for this to complete my task

**Comment by mahabubx7** [comment]
@harshmangalam plz check the PR #97 I made

👍🏼
