### ISSUE TITLE
Link to user profile in post lists page

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#42]
When user click on post author
- avatar
- name
- username

navigate to their profile page

**Comment by WangGithub0** [comment]
Hi @harshmangalam , could I work on this issue? thanks

**Comment by WangGithub0** [comment]
Hi @harshmangalam, I tried to setup according to the README, and successfully "Create and sync schema in your database", but when I run "pnpm dev", I met this error, could you help me? thanks.

<img width="810" alt="image" src="https://github.com/harshmangalam/qwik-x/assets/20795443/4914324d-1135-49bd-a49e-cbcbe0cdb15c">

<img width="1625" alt="image" src="https://github.com/harshmangalam/qwik-x/assets/20795443/80560e1c-40ae-4363-9a68-fc98fb587932">

**Comment by harshmangalam** [comment]
Use neon database url because i recently moved express server which was using postgres pool connection to neon serverless connection

**Comment by harshmangalam** [comment]
You can create postgres instance here 
https://neon.tech/

**Comment by WangGithub0** [comment]
@harshmangalam thanks for your reply.
I tried using neon, but it throw the error "connection is insecure (try using `sslmode=require`)", where should I add 'sslmode'? thanks
<img width="724" alt="image" src="https://github.com/harshmangalam/qwik-x/assets/20795443/ec8ffe48-4dc5-4e37-ad73-eb1fdcec1757">

**Comment by harshmangalam** [comment]
```
DRIZZLE_DATABASE_URL="postgres://harshmangalam:123456@localhost:5432/qwikx?ssl=true"
```
