### ISSUE TITLE
Add user suggestions link for small screen

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#44]
Currently the right sidebar show the  `Show more` link for more user suggestions but sidebar is hidden for smaller screen. Add an icon in bottom navigations for user suggestions and connect it to  `/suggestions` link

**Comment by Stormbreakerr20** [comment]
Can you assign it to me?

**Comment by harshmangalam** [comment]
Hacktobefest accepted tag is for when your PR will be successfully  merged.

**Comment by Stormbreakerr20** [comment]
Ok !! but can you assign it to me?

**Comment by Stormbreakerr20** [comment]
Hey @harshmangalam I have added the suggestion link in mobile view/ bottom nav, I have made a PR regarding the same....Please check once
