### ISSUE TITLE
font changes in 'wireframe' theme

### ISSUE THREAD

**Issue by udeet27** [harshmangalam/qwik-x#60]
- you can see that the font changes only for the 'wireframe' theme. A theme ideally should just change the colors not the font. 
- Not sure if this was intentional or not because font remains constant for all other themes.
- Also Comic Sans is ofcourse not an ideal font.
<img width="960" alt="image" src="https://github.com/harshmangalam/qwik-x/assets/75639351/449325cc-d334-4db5-83ff-6b627ef9b1d3">

**Comment by harshmangalam** [comment]
I have just used daisyui themes that handle color, background, spacing and font related properties by default.
I agree `Comic Sans is of course not an ideal font ` If you want you can contribute by adding some nice font.

**Comment by udeet27** [comment]
Ohh understood. Maybe can override the font just for the 'wireframe' theme. I'll look into it thanks.
