### ISSUE TITLE
Add open graphs and meta tags

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/qwik-x#7]
Add different different meta tags .
Add open graph tags for social sharing.

**Comment by Akhaled19** [comment]
Hi, so you want to add open graph meta tags for post-component?

**Comment by harshmangalam** [comment]
Add og tags and meta title & description  to the root of the component --->  root.tsx

**Comment by Akhaled19** [comment]
ok, I want to give it a try

**Comment by Akhaled19** [comment]
I couldn't get the project up and running following the command lines in the readme file. If anyone has any tips lmk

**Comment by harshmangalam** [comment]
Hey @Akhaled19  I have added Setup section in repo README.md let me know if you face any issues during setup.

**Comment by Krish-Panchani** [comment]
I want to work on this.

**Comment by harshmangalam** [comment]
Just raise PR I will merge
